# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish'
        required: false
        default: ''
  release:
    types: [published]

# Needed for nx-set-shas when run on the main branch
permissions:
  actions: read
  contents: read

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      NX_BASE: origin/main~1
      NX_HEAD: origin/main
      NODE_AUTH_TOKEN: ${{secrets.npm_token}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Set shas
        uses: nrwl/nx-set-shas@v4

      - name: Build artifact
        run: npx nx affected -t lint test test:types build

      - name: Apply updated version and publish
        run: |
          # Use the version from the workflow input if it`s seo
          VERSION=${{ github.event.inputs.version || github.ref_name }}
          npx nx release version --specifier=$VERSION
          npx nx release publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          NPM_CONFIG_PROVENANCE: true
